enum ACTIONTYPE {
  MESSENGER_LOADING = "MESSENGER_LOADING",
  MESSENGER_LOADED = "MESSENGER_LOADED",
  RECIEVING_MESSAGE = "RECIEVING_MESSAGE",
  RECIEVING_MESSAGE_INFO = "RECIEVING_MESSAGE_INFO",
  SENDING_MESSAGE = "SENDING_MESSAGE",
  RESET_UNREAD = "RESET_UNREAD",
  UPDATE_LASTSEEN = "UPDATE_LASTSEEN",

  //Auth
  AUTH_LOADING = "AUTH_LOADING",
  Auth_COMPLETED = "AUTH_COMPLETED",
}

export default ACTIONTYPE;
